file_format: "1"
id: roadrunner
name: Roadrunner/Sweep
type: shield
url: https://github.com/nathansbradshaw/zmk-roadrunner
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - roadrunner_left
  - roadrunner_right
