file_format: "1"
id: roadrunner
name: RoadRunner
type: shield
url: https://github.com/nathansbradshaw/zmk-roadrunner
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
siblings:
  - cradio_left
  - cradio_right
